// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"context"
	"database/sql"
	"github.com/yangchnet/skeleton/internal/hello/data"
)

// Injectors from wire.go:

func InitService(ctx context.Context, db *sql.DB) service {
	helloInterface := data.NewStore(db)
	serviceService := service{
		hello: helloInterface,
	}
	return serviceService
}
