// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"context"
	"github.com/yangchnet/skeleton/internal/echo/biz"
	"github.com/yangchnet/skeleton/internal/echo/conf"
	"github.com/yangchnet/skeleton/internal/echo/data"
)

// Injectors from wire.go:

func InitService(ctx context.Context, conf2 *conf.Bootstrap) (*EchoService, error) {
	client, err := data.NewEnt(ctx, conf2)
	if err != nil {
		return nil, err
	}
	cacheInterface := data.NewCache(ctx, conf2)
	echoRepo := data.NewData(ctx, client, cacheInterface)
	echoCase := biz.NewEchoCase(ctx, echoRepo)
	echoService := NewEchoService(ctx, echoCase)
	return echoService, nil
}
