server:
  http:
    host: 0.0.0.0
    port: 10000
    timeout: 1s
token:
  secret: 326c9f73b0f45705a73eb020a32d790a
  expiration: 7200 # seconds
log:
  level: 0 # 0: debug, 1: info, 2: warn, 3: error, 4: panic, 5, fatal
  formatter: text # text/json
  disable_caller: false # log中不记录文件名及行号
  disable_color: false # 无颜色输出log
  enable_abs_path: true # 输出文件名的完整的路径
  enable_func: false # 输出打印log的函数名
  ignore_basic_fields: false # 日志中不记录时间、文件等信息
