// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package service

import (
	"context"
	"database/sql"
	"github.com/yangchnet/skeleton/internal/iam/data"
)

// Injectors from wire.go:

func InitService(ctx context.Context, db *sql.DB) service {
	iamInterface := data.NewStore(db)
	serviceService := service{
		iamData: iamInterface,
	}
	return serviceService
}
