// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"context"
	"github.com/yangchnet/skeleton/internal/iam/biz"
	"github.com/yangchnet/skeleton/internal/iam/conf"
	"github.com/yangchnet/skeleton/internal/iam/data"
)

// Injectors from wire.go:

func InitService(ctx context.Context, conf2 *conf.Bootstrap) (*service, error) {
	client, err := data.NewEnt(ctx, conf2)
	if err != nil {
		return nil, err
	}
	cacheInterface := data.NewCache(ctx, conf2)
	iamRepo := data.NewData(ctx, client, cacheInterface)
	iamCase := biz.NewIamCase(ctx, iamRepo)
	serviceService := NewIamService(iamCase)
	return serviceService, nil
}
