// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthzPolicy is the predicate function for authzpolicy builders.
type AuthzPolicy func(*sql.Selector)

// BindUserRole is the predicate function for binduserrole builders.
type BindUserRole func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
