// Code generated by "makestatic"; DO NOT EDIT.

package static

var Files = map[string]string{
	"api.swagger.json": `{
  "swagger": "2.0",
  "info": {
    "title": "Project Skeleton",
    "version": "0.0.1",
    "contact": {
      "name": "Project Skeleton"
    }
  },
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/app/evidences": {
      "post": {
        "summary": "打招呼",
        "description": "create evidence",
        "operationId": "SayHelloAggr",
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/v1SayHelloAggrResponse"
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/v1SayHelloAggrRequest"
            }
          }
        ],
        "tags": [
          "HelloAggr"
        ]
      }
    }
  },
  "definitions": {
    "v1SayHelloAggrRequest": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "title": "hello message"
        }
      }
    },
    "v1SayHelloAggrResponse": {
      "type": "object",
      "properties": {
        "echo_message": {
          "type": "string",
          "title": "hello echo"
        }
      }
    }
  },
  "securityDefinitions": {
    "BearerAuth": {
      "type": "apiKey",
      "description": "The Authorization header must be set to Bearer followed by a space and a token. For example, 'Bearer vHUabiBEIKi8n1RdvWOjGFulGSM6zunb'.",
      "name": "Authorization",
      "in": "header"
    },
    "PasetoAuth": {
      "type": "apiKey",
      "description": "PASETO is a security token format that uses protocol versioning instead of in-band negotiation to provide maximum security but still allow seamless migrations.",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "BearerAuth": [],
      "PasetoAuth": []
    }
  ]
}
`,
}
