// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yangchnet/skeleton/internal/echo/data/ent/echo"
)

// EchoCreate is the builder for creating a Echo entity.
type EchoCreate struct {
	config
	mutation *EchoMutation
	hooks    []Hook
}

// SetMessage sets the "message" field.
func (ec *EchoCreate) SetMessage(s string) *EchoCreate {
	ec.mutation.SetMessage(s)
	return ec
}

// SetEchoMessage sets the "echo_message" field.
func (ec *EchoCreate) SetEchoMessage(s string) *EchoCreate {
	ec.mutation.SetEchoMessage(s)
	return ec
}

// SetCreateTime sets the "create_time" field.
func (ec *EchoCreate) SetCreateTime(t time.Time) *EchoCreate {
	ec.mutation.SetCreateTime(t)
	return ec
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (ec *EchoCreate) SetNillableCreateTime(t *time.Time) *EchoCreate {
	if t != nil {
		ec.SetCreateTime(*t)
	}
	return ec
}

// SetUpdateTime sets the "update_time" field.
func (ec *EchoCreate) SetUpdateTime(t time.Time) *EchoCreate {
	ec.mutation.SetUpdateTime(t)
	return ec
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (ec *EchoCreate) SetNillableUpdateTime(t *time.Time) *EchoCreate {
	if t != nil {
		ec.SetUpdateTime(*t)
	}
	return ec
}

// SetDeleteTime sets the "delete_time" field.
func (ec *EchoCreate) SetDeleteTime(t time.Time) *EchoCreate {
	ec.mutation.SetDeleteTime(t)
	return ec
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (ec *EchoCreate) SetNillableDeleteTime(t *time.Time) *EchoCreate {
	if t != nil {
		ec.SetDeleteTime(*t)
	}
	return ec
}

// Mutation returns the EchoMutation object of the builder.
func (ec *EchoCreate) Mutation() *EchoMutation {
	return ec.mutation
}

// Save creates the Echo in the database.
func (ec *EchoCreate) Save(ctx context.Context) (*Echo, error) {
	var (
		err  error
		node *Echo
	)
	ec.defaults()
	if len(ec.hooks) == 0 {
		if err = ec.check(); err != nil {
			return nil, err
		}
		node, err = ec.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EchoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ec.check(); err != nil {
				return nil, err
			}
			ec.mutation = mutation
			if node, err = ec.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ec.hooks) - 1; i >= 0; i-- {
			if ec.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ec.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ec.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EchoCreate) SaveX(ctx context.Context) *Echo {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EchoCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EchoCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *EchoCreate) defaults() {
	if _, ok := ec.mutation.CreateTime(); !ok {
		v := echo.DefaultCreateTime()
		ec.mutation.SetCreateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ec *EchoCreate) check() error {
	if _, ok := ec.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "Echo.message"`)}
	}
	if v, ok := ec.mutation.Message(); ok {
		if err := echo.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Echo.message": %w`, err)}
		}
	}
	if _, ok := ec.mutation.EchoMessage(); !ok {
		return &ValidationError{Name: "echo_message", err: errors.New(`ent: missing required field "Echo.echo_message"`)}
	}
	if _, ok := ec.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Echo.create_time"`)}
	}
	return nil
}

func (ec *EchoCreate) sqlSave(ctx context.Context) (*Echo, error) {
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ec *EchoCreate) createSpec() (*Echo, *sqlgraph.CreateSpec) {
	var (
		_node = &Echo{config: ec.config}
		_spec = &sqlgraph.CreateSpec{
			Table: echo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: echo.FieldID,
			},
		}
	)
	if value, ok := ec.mutation.Message(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: echo.FieldMessage,
		})
		_node.Message = value
	}
	if value, ok := ec.mutation.EchoMessage(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: echo.FieldEchoMessage,
		})
		_node.EchoMessage = value
	}
	if value, ok := ec.mutation.CreateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldCreateTime,
		})
		_node.CreateTime = value
	}
	if value, ok := ec.mutation.UpdateTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldUpdateTime,
		})
		_node.UpdateTime = &value
	}
	if value, ok := ec.mutation.DeleteTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldDeleteTime,
		})
		_node.DeleteTime = &value
	}
	return _node, _spec
}

// EchoCreateBulk is the builder for creating many Echo entities in bulk.
type EchoCreateBulk struct {
	config
	builders []*EchoCreate
}

// Save creates the Echo entities in the database.
func (ecb *EchoCreateBulk) Save(ctx context.Context) ([]*Echo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Echo, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EchoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EchoCreateBulk) SaveX(ctx context.Context) []*Echo {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EchoCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EchoCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}
