// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yangchnet/skeleton/internal/echo/data/ent/echo"
	"github.com/yangchnet/skeleton/internal/echo/data/ent/predicate"
)

// EchoUpdate is the builder for updating Echo entities.
type EchoUpdate struct {
	config
	hooks    []Hook
	mutation *EchoMutation
}

// Where appends a list predicates to the EchoUpdate builder.
func (eu *EchoUpdate) Where(ps ...predicate.Echo) *EchoUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetMessage sets the "message" field.
func (eu *EchoUpdate) SetMessage(s string) *EchoUpdate {
	eu.mutation.SetMessage(s)
	return eu
}

// SetEchoMessage sets the "echo_message" field.
func (eu *EchoUpdate) SetEchoMessage(s string) *EchoUpdate {
	eu.mutation.SetEchoMessage(s)
	return eu
}

// SetCreateTime sets the "create_time" field.
func (eu *EchoUpdate) SetCreateTime(t time.Time) *EchoUpdate {
	eu.mutation.SetCreateTime(t)
	return eu
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (eu *EchoUpdate) SetNillableCreateTime(t *time.Time) *EchoUpdate {
	if t != nil {
		eu.SetCreateTime(*t)
	}
	return eu
}

// SetUpdateTime sets the "update_time" field.
func (eu *EchoUpdate) SetUpdateTime(t time.Time) *EchoUpdate {
	eu.mutation.SetUpdateTime(t)
	return eu
}

// SetDeleteTime sets the "delete_time" field.
func (eu *EchoUpdate) SetDeleteTime(t time.Time) *EchoUpdate {
	eu.mutation.SetDeleteTime(t)
	return eu
}

// Mutation returns the EchoMutation object of the builder.
func (eu *EchoUpdate) Mutation() *EchoMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EchoUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		if err = eu.check(); err != nil {
			return 0, err
		}
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EchoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = eu.check(); err != nil {
				return 0, err
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			if eu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EchoUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EchoUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EchoUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EchoUpdate) check() error {
	if v, ok := eu.mutation.Message(); ok {
		if err := echo.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Echo.message": %w`, err)}
		}
	}
	return nil
}

func (eu *EchoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   echo.Table,
			Columns: echo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: echo.FieldID,
			},
		},
	}
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Message(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: echo.FieldMessage,
		})
	}
	if value, ok := eu.mutation.EchoMessage(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: echo.FieldEchoMessage,
		})
	}
	if value, ok := eu.mutation.CreateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldCreateTime,
		})
	}
	if value, ok := eu.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldUpdateTime,
		})
	}
	if value, ok := eu.mutation.DeleteTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldDeleteTime,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{echo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// EchoUpdateOne is the builder for updating a single Echo entity.
type EchoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EchoMutation
}

// SetMessage sets the "message" field.
func (euo *EchoUpdateOne) SetMessage(s string) *EchoUpdateOne {
	euo.mutation.SetMessage(s)
	return euo
}

// SetEchoMessage sets the "echo_message" field.
func (euo *EchoUpdateOne) SetEchoMessage(s string) *EchoUpdateOne {
	euo.mutation.SetEchoMessage(s)
	return euo
}

// SetCreateTime sets the "create_time" field.
func (euo *EchoUpdateOne) SetCreateTime(t time.Time) *EchoUpdateOne {
	euo.mutation.SetCreateTime(t)
	return euo
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (euo *EchoUpdateOne) SetNillableCreateTime(t *time.Time) *EchoUpdateOne {
	if t != nil {
		euo.SetCreateTime(*t)
	}
	return euo
}

// SetUpdateTime sets the "update_time" field.
func (euo *EchoUpdateOne) SetUpdateTime(t time.Time) *EchoUpdateOne {
	euo.mutation.SetUpdateTime(t)
	return euo
}

// SetDeleteTime sets the "delete_time" field.
func (euo *EchoUpdateOne) SetDeleteTime(t time.Time) *EchoUpdateOne {
	euo.mutation.SetDeleteTime(t)
	return euo
}

// Mutation returns the EchoMutation object of the builder.
func (euo *EchoUpdateOne) Mutation() *EchoMutation {
	return euo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EchoUpdateOne) Select(field string, fields ...string) *EchoUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Echo entity.
func (euo *EchoUpdateOne) Save(ctx context.Context) (*Echo, error) {
	var (
		err  error
		node *Echo
	)
	if len(euo.hooks) == 0 {
		if err = euo.check(); err != nil {
			return nil, err
		}
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EchoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = euo.check(); err != nil {
				return nil, err
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			if euo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = euo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, euo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EchoUpdateOne) SaveX(ctx context.Context) *Echo {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EchoUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EchoUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EchoUpdateOne) check() error {
	if v, ok := euo.mutation.Message(); ok {
		if err := echo.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "Echo.message": %w`, err)}
		}
	}
	return nil
}

func (euo *EchoUpdateOne) sqlSave(ctx context.Context) (_node *Echo, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   echo.Table,
			Columns: echo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: echo.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Echo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, echo.FieldID)
		for _, f := range fields {
			if !echo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != echo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Message(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: echo.FieldMessage,
		})
	}
	if value, ok := euo.mutation.EchoMessage(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: echo.FieldEchoMessage,
		})
	}
	if value, ok := euo.mutation.CreateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldCreateTime,
		})
	}
	if value, ok := euo.mutation.UpdateTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldUpdateTime,
		})
	}
	if value, ok := euo.mutation.DeleteTime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: echo.FieldDeleteTime,
		})
	}
	_node = &Echo{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{echo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
