server:
  http:
    host: 0.0.0.0
    port: 10000
    timeout: 1s
  grpc:
    service_name: echo_service
    host: 0.0.0.0
    port: 10001
    timeout: 1s
data:
  database:
    driver: mysql
    dsn: root:insecure@tcp(127.0.0.1:13306)/echo?parseTime=true&charset=utf8mb4&loc=Local
# TODO: logger settings
# options and debug
